// <auto-generated />
using System;
using Infraestructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(DatabasePostgresContext))]
    [Migration("20220910190620_CreateTableBook")]
    partial class CreateTableBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AUTHOR");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int>("PageNumber")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("PAGE_NUMBER");

                    b.Property<float>("Price")
                        .HasPrecision(2)
                        .IsRequired()
                        .HasColumnType("real")
                        .HasColumnName("PRICE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("BOOK", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
